### ISSUE TITLE
Don't run in privileged mode on a Raspberry Pi

### ISSUE THREAD

**Issue by proffalken** [BudgetSmartHome/hubitat2prom#4]
When trying to run the container on a Raspberry Pi, the container must be run in privileged mode otherwise you encounter the following error:

```
Fatal Python error: pyinit_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0x76fdd390 (most recent call first):
<no Python frame>
```

We should find a way to get the container to run without needing privileged mode so we can run more securely.

**Comment by patoarvizu** [comment]
Just FYI, I was able to run `proffalken/hubitat2prom:sha-96522aa` on arm64 (Raspberry Pi 4, Kubernetes 1.19, Ubuntu 20.04.1) without requiring privileged mode. In fact I explicitly specified:
```
securityContext:
  privileged: false
  allowPrivilegeEscalation: false
```
And things worked as expected! (I didn't confirm if other image tags were working as well.)

**Comment by proffalken** [comment]
Thanks, I'll try it again on my kit and see if I get the same - please note that we're moving the docker container to Github Container Registry in the future so you may need to update your links!

**Comment by proffalken** [comment]
@patoarvizu - Assuming you're still using this, can you try the latest container as well please? It's now at ghcr.io/budgetsmarthome/hubitat2prom.  It seems to work for me..

**Comment by patoarvizu** [comment]
Thanks for the heads up! I don't have access to my home cluster right now but I should be able to test soon and I'll report back.
Is the `proffalken/hubitat2prom` repo being deprecated?

**Comment by proffalken** [comment]
@patoarvizu awesome, thanks.

Yeah, I'm moving all this stuff under the BudgetSmartHome organisation to keep it in sync with my blog: www.budgetsmarthome.co.uk

**Comment by patoarvizu** [comment]
Everything looks good! 👍

**Comment by proffalken** [comment]
Amazing, thanks, I'll close this off now then!
