### ISSUE TITLE
metric name sanitizing

### ISSUE THREAD

**Issue by demslam** [BudgetSmartHome/hubitat2prom#9]
First off thank you very much for this. I am trying to get my Aeon Home Energy meter to output current information. When I select the "current-clamp-#" or "power-clamp-#" i get an error in Prometheus "unsupported character in float". 
![image](https://user-images.githubusercontent.com/5873161/124314628-8cf4e800-db27-11eb-81bc-5072f9e6fb1b.png)

Looking at Prometheus doc the "-" character does not seem valid
https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels

is there a way to overwrite the metrics name?

Again thank you.

**Comment by demslam** [comment]
So i am not great with code but i seemed to have solved it with updated line 48 "metric_name" with what you had for sanitizing the device label

#                       "metric_name": f"{attrib['name']}",
                        "metric_name": f"{attrib['name'].lower().replace(' ','_').replace('-','_')}",

**Comment by proffalken** [comment]
Hey @demslam - thanks for logging this, I don't have any devices right now that output a string as the value, so I'd completely missed it.

I've updated the code as suggested and the results are in #10 - can I ask you to test the Docker container for me as well please? You can find the new version at https://github.com/BudgetSmartHome/hubitat2prom/pkgs/container/hubitat2prom/3605876 - once you're happy that this works, I'll merge the code and you'll be able to revert to `hubitat2prom:latest` in your Docker setup

**Comment by demslam** [comment]
Hello @proffalken just pulled the docker you linked and it works. Thank you very much

**Comment by proffalken** [comment]
Thanks @demslam - I've just merged the changes now, give it 20 minutes or so to build the containers then you should be able to pull `:latest` and have it work instead of using the commit-specific container.

Let me know if you hit any issues,

**Comment by demslam** [comment]
Hello @proffalken just did a pull of the proffalken/hubitat2prom:latest and it looks like the change hasn't been implemented.

**Comment by proffalken** [comment]
OK, thanks @demslam, I'll check the build shortly

**Comment by proffalken** [comment]
@demslam - I've found the issue... ;)

I recently moved the container out from my personal space on hub.docker.com and into the BudgetSmartHome space on Gihub Container Registry.  Instead of using `proffalken/hubitat2prom:latest` you'll want to be using `ghcr.io/budgetsmarthome/hubitat2prom:latest`.  That should work.

**Comment by demslam** [comment]
Works great thank you!
